//
export const FETCH_TASKS_START = 'FETCH_TASKS_START'
export const FETCH_TASKS_SUCCESS = 'FETCH_TASKS_SUCCESS'
export const FETCH_TASKS_ERROR = 'FETCH_TASKS_ERROR'
export const CHANGE_TASK = 'CHANGE_TASK'
export const CHANGE_TASK_SUCCESS = 'CHANGE_TASK_SUCCESS'
export const CHANGE_TASK_ERROR = 'CHANGE_TASK_ERROR'

